name: Install Lix
description: Install Lix on the current system

runs:
  using: composite

  steps:
    - uses: DeterminateSystems/nix-installer-action@v20
      with:
        source-url: 'https://install.lix.systems/lix/lix-installer-${{ fromJSON(''{"X64":"x86_64","X86":"i686","ARM64":"aarch64","ARM":"armv7l"}'')[runner.arch] }}-${{ fromJSON(''{"Linux":"linux","macOS":"darwin","Windows":"windows"}'')[runner.os] }}'
        extra-conf: experimental-features = flakes nix-command pipe-operator
