name: check
run-name: Checking outputs
on: push

jobs:
  check:
    name: Check outputs (${{ matrix.system }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            system: x86_64-linux
          - os: macos-latest
            system: aarch64-darwin

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@v2026-02-22
      - name: Check flake
        run: nix flake check --show-trace
