name: tangled
run-name: Pushing repository to Tangled
on: push

permissions:
  contents: read
  pull-requests: read

jobs:
  tangled:
    name: Push repository to Tangled
    runs-on: ubuntu-latest

    steps:
      - uses: gwennlbh/to-tangled@v0.6
        with:
          knot: knot.toodeluna.net
          repo: toodeluna.net/config
          ssh-key: ${{ secrets.TANGLED_KEY }}
