name: tangled
run-name: Push repository to Tangled
on: push

permissions:
  contents: read
  pull-requests: read

jobs:
  tangled:
    runs-on: ubuntu-latest

    steps:
      - uses: toodeluna/to-tangled@86e06bd41bdf19932d668f5d46128eb485e25cd1
        with:
          knot: knot.toodeluna.net
          repo: toodeluna.net/config
          ssh-key: ${{ secrets.TANGLED_KEY }}
